# Numpy (Numeric python)
    패키지 이름과 같이 mathematical한 python 활용을 위한 python package
    선형대수학 구현과 과학적 computing 연산을 위한 함수를 제공합니다.
    
    (key)np array 다차원 배열을 사용하여 vector의 산술 연산이 가능합니다.
    broadcasting을 활용하여 shape(형태 혹은 모양)이 다른 데이터의 연산이 가능합니다.
    - 기존 언어에서는 제공 x
    - 굉장히 powerful한 기능으로써 데이터 연산에 굉장히 효율이 좋다.

## 1. Numpy 설치와 import
선행 학습을 통해 class와 함수에서 패키지와 클래스를 불러들여 사용할 수 있다고 배웠습니다.
다만 직접 작성한 클래스가 아닐경우, 그리고 현재 컴퓨터에 사용해야 할 패키지가 없을경우 간단한 명령어로 설치가능.

    conda, pip 명령어 : python 라이브러리 관리 프로그램으로 
               오픈소스라이브러리를 간편하게 설치 할 수 있도록 하는 명령어

    콘솔창에서 실행 시
    pip install [패키지명]
    conda install [패키지명]

    주피터 노트북으로 실행 시
    !pip install [패키지명]

    아나콘다 환경으로 python 환경설정 시 기본적으로 Numpy 설치가 되어있음
    -> 이미 설치되어있기 때문에 skip
   

In [2]:
# numpy를 np라는 nickname으로 import해서 사용합니다.
import numpy as np
# 관례적으로 np라는 약자를 많이 사용한다고 한다.
# python을 사용하는 대부분의 user들이 사용하고 있는 닉네임이니 되도록 지키자!

## 2. Numpy function
    numpy는 computing 연산을 위한 다양한 연산 함수를 제공합니다.
    자주 사용하는 연산 함수 위주로 살펴보겠습니다.
    
    연산 함수의 기본 구조
    np.sum(연산 대상, axis=연산방향)

In [3]:
# 함수 예제를 위한 데이터셋
test_list = [1, 2, 3, 4]

test_list2 = [[1, 3], [5, 7]]

test_flist = [1, 3.14, -4.5]

test_list_2nd = [[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]]

test_list_3rd = [[[1, 2, 3, 4],
              [5, 6, 7, 8]],
              
              [[1, 2, 3, 4],
               [5, 6, 7, 8]],

              [[1, 2, 3, 4],
               [5, 6, 7, 8]]]
test_exp = [0, 1, 10]

test_nan = [0, np.nan, np.inf]

### 수리연산
    - prod()
    - dot()
    - sum()
    - cumprod()
    - cumsum()
    - abs()
    - sqaure()
    - sqrt()
    - exp()
    - log()
### 통계연산
    - mean()
    - std()
    - var()
    - max()
    - min()
    - argmax()
    - argmin()
### 로직연산
    - arange()
    - isnan()
    - isinf()
    - unique()
### 기하
    - shape()
    - reshape()
    - ndim()
    - transpose()
    
각종 연산 참고 : https://numpy.org/doc/stable/reference/routines.math.html

## 3. Numpy array (배열, 행렬)
    - numpy 연산의 기본이 되는 데이터 구조입니다.
    - list보다 간편하게 생성 가능하며 연산이 빠르다는 장점이 있습니다.
    - 앞서 언급한 broad casting 연산을 지원합니다.
    - 같은 type의 data만 저장할 수 있습니다.
    
    array 또한 numpy의 기본 함수로 생성 가능합니다.
    array 함수의 기본 호출 구조는 아래와 같습니다.
    
    ex) np.array(배열 변환 대상 data)
    ex) np.arange(start, end, step_forward) : 기존 range와 같은 argument 형태를 입력 받는다

In [5]:
# 위의 개념을 이용해 앞서 선언한 list들을 array로 변환
test_array = np.array(test_list)
test_array2 = np.array(test_list2)
test_farray = np.array(test_flist)

test_array_2nd = np.array(test_list_2nd)
test_array_3rd = np.array(test_list_3rd)

print(test_array)
print(test_array2)
print(test_farray)
print(test_array_2nd)
print(test_array_3rd)

[1 2 3 4]
[[1 3]
 [5 7]]
[ 1.    3.14 -4.5 ]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]


In [6]:
# np.aramge 함수로 생성
range_array = np.arange(10)
print(range_array)

[0 1 2 3 4 5 6 7 8 9]


### 3-1. 특수한 형태의 array를 함수를 이용해 생성
    함수 호출의 기본 구조는 아래와 같습니다. 각 함수들은 이름에 걸맞는 array들을 생성합니다.
    
        ex) np.ones([자료구조 shape])
        자료구조 shape은 정수, []리스트, ()튜플로만 입력이 가능합니다.
        
        함수 list
        - ones
        - zeros
        - empty
        - eye

### 3-2. array 속성 및 내장 함수
np.array에는 굉장히 유용한 수리, 통계 연산을 위한 함수가 갖추어져 있습니다. 다차원 기하학적 연산을 위한 함수도 함께 살펴보겠습니다.